# -*- coding: utf-8 -*-
"""BondDuration_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBIXgU7F2q1yBtXWuKPjED5DyegQZ9Sk
"""

def getBondDuration(y, face, couponRate, m, ppy=1):
    coupon = face * couponRate / ppy
    pv_cf = []

    for t in range(1, m+1):
        pv_cf.append((t * ppy) * (coupon / ((1 + y/ppy) ** (t * ppy))))

    pv_cf.append(m * ppy * (face / ((1 + y/ppy) ** (m * ppy))))
    bondPrice = getBondPrice(y, face, couponRate, m, ppy)
    bondDuration = sum(pv_cf) / bondPrice
    return bondDuration

y = 0.03
face = 2000000
couponRate = 0.04
m = 10
ppy = 1

print("Bond Duration:", getBondDuration(y, face, couponRate, m, ppy))