# -*- coding: utf-8 -*-
"""BondPrice_E_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FSgrsv8WixoVyG-HTRpbY-6vC7nvtaGB
"""

def getBondPrice_E(face, couponRate, yc):
    bondPrice = 0
    for t, y in enumerate(yc, start=1):
        if t < m:
            bondPrice += (face * couponRate) / ((1 + y) ** t)
        else:
            bondPrice += (face * (1 + couponRate)) / ((1 + y) ** t)
    return bondPrice

yc = [.010,.015,.020,.025,.030]
face = 2000000
couponRate = .04

print("Bond Price with Enumerated YC:", getBondPrice_E(face, couponRate, yc))