# -*- coding: utf-8 -*-
"""WhoAmI_File

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yPEg1UF3ZlbN1eHr2JUH8TvgX0DX0Jvt
"""

def WhoAmI():
  return ('lg3372')